version: "3"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./.docker/mysql/dump/:/var/lib/mysql
    networks:
      - internal

  drupal:
    image: drupal:8.7.8-fpm-alpine
    container_name: drupal
    depends_on:
      - mysql
    restart: unless-stopped
    networks:
      - internal
      - external
    volumes:
      - ./drupal:/var/www/html

  webserver:
    image: nginx:1.17.4-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./drupal:/var/www/html
      - ./.docker/nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
    networks:
      - external

  phpmyadmin:
    depends_on:
      - mysql
    restart: always
    image: phpmyadmin/phpmyadmin:latest
    links:
      - mysql
    networks:
      - internal
      - external
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql

  # certbot:
  #   depends_on:
  #     - webserver
  #   image: certbot/certbot
  #   container_name: certbot
  #   volumes:
  #     - certbot-etc:/etc/letsencrypt
  #     - ./drupal:/var/www/html
  #   command: certonly --webroot --webroot-path=/var/www/html --email gulbrich@ciandt.com --agree-tos --no-eff-email --staging -d localhost

networks:
  external:
    driver: bridge
  internal:
    driver: bridge

volumes:
  drupal:
  certbot-etc: